jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    on:
      push:
        branches:
          - main  # Triggers deployment on every push to main

    permissions: 
      contents: write  # ✅ This grants GitHub Actions permission to push to gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set environment variable from GitHub Secret
        run: echo "REACT_APP_CONTACT_NUMBER=${{ secrets.REACT_APP_CONTACT_NUMBER }}" >> $GITHUB_ENV

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
